--A1  CSDL Qu?n lý ?i?m sinh viên
-- B?ng khoa
CREATE TABLE DMKHOA (
    MAKHOA CHAR(2) PRIMARY KEY,
    TENKHOA NVARCHAR2(30)
);

-- B?ng môn h?c
CREATE TABLE DMMH (
    MAMH CHAR(2) PRIMARY KEY,
    TENMH NVARCHAR2(35),
    SOTIET NUMBER(3)
);

-- B?ng sinh viên
CREATE TABLE DMSV (
    MASV CHAR(3) PRIMARY KEY,
    HOSV NVARCHAR2(30),
    TENSV NVARCHAR2(10),
    PHAI NVARCHAR2(3),
    NGAYSINH DATE,
    NOISINH NVARCHAR2(25),
    MAKH CHAR(2),
    HOCBONG NUMBER(10,0),
    FOREIGN KEY (MAKH) REFERENCES DMKHOA(MAKHOA)
);

-- B?ng k?t qu?
CREATE TABLE KETQUA (
    MASV CHAR(3),
    MAMH CHAR(2),
    DIEM NUMBER(4,2),
    PRIMARY KEY (MASV, MAMH),
    FOREIGN KEY (MASV) REFERENCES DMSV(MASV),
    FOREIGN KEY (MAMH) REFERENCES DMMH(MAMH)
);

--insert
--DMKHOA
INSERT INTO DMKHOA VALUES ('01', N'CNTT');
INSERT INTO DMKHOA VALUES ('02', N'Kinh t?');
INSERT INTO DMKHOA VALUES ('03', N'Ngo?i ng?');
INSERT INTO DMKHOA VALUES ('04', N'Xây d?ng');
INSERT INTO DMKHOA VALUES ('05', N'C? khí');
--DMMH
INSERT INTO DMMH VALUES ('MH', N'M?ng máy tính', 45);
INSERT INTO DMMH VALUES ('DL', N'C? s? d? li?u', 60);
INSERT INTO DMMH VALUES ('CT', N'L?p trình C', 50);
INSERT INTO DMMH VALUES ('JA', N'Java', 55);
INSERT INTO DMMH VALUES ('PY', N'Python', 40);
--DMSV
INSERT INTO DMSV VALUES ('S01', N'Nguy?n', N'An', N'Nam', TO_DATE('2003-01-01','YYYY-MM-DD'), N'HCM', '01', 1000000);
INSERT INTO DMSV VALUES ('S02', N'Tr?n', N'Bình', N'Nam', TO_DATE('2003-02-02','YYYY-MM-DD'), N'Hà N?i', '01', 0);
INSERT INTO DMSV VALUES ('S03', N'Lê', N'C??ng', N'Nam', TO_DATE('2003-03-03','YYYY-MM-DD'), N'?à N?ng', '02', 500000);
INSERT INTO DMSV VALUES ('S04', N'Ph?m', N'Dung', N'N?', TO_DATE('2003-04-04','YYYY-MM-DD'), N'HCM', '03', 0);
INSERT INTO DMSV VALUES ('S05', N'Hoàng', N'Em', N'N?', TO_DATE('2003-05-05','YYYY-MM-DD'), N'Hu?', '01', 200000);
--KETQUA
INSERT INTO KETQUA VALUES ('S01','MH',8);
INSERT INTO KETQUA VALUES ('S01','DL',7);
INSERT INTO KETQUA VALUES ('S02','CT',6);
INSERT INTO KETQUA VALUES ('S03','JA',9);
INSERT INTO KETQUA VALUES ('S04','PY',7.5);


--A2. CSDL Qu?n lý ?? án công ty
--T?o b?ng
-- Phòng ban
CREATE TABLE PHONGBAN (
    MAPHG NUMBER PRIMARY KEY,
    TENPHG NVARCHAR2(30)
);

-- Nhân viên
CREATE TABLE NHANVIEN (
    MANV NUMBER PRIMARY KEY,
    TENNV NVARCHAR2(30),
    LUONG NUMBER,
    MAPHG NUMBER,
    FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
);

-- ??a ?i?m phòng
CREATE TABLE DIADIEM_PHG (
    MAPHG NUMBER,
    DIADIEM NVARCHAR2(30),
    PRIMARY KEY (MAPHG, DIADIEM),
    FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
);

-- ?? án
CREATE TABLE DEAN (
    MADA NUMBER PRIMARY KEY,
    TENDA NVARCHAR2(30),
    MAPHG NUMBER,
    FOREIGN KEY (MAPHG) REFERENCES PHONGBAN(MAPHG)
);

-- Phân công
CREATE TABLE PHANCONG (
    MANV NUMBER,
    MADA NUMBER,
    THOIGIAN NUMBER,
    PRIMARY KEY (MANV, MADA),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MADA) REFERENCES DEAN(MADA)
);

-- Thân nhân
CREATE TABLE THANNHAN (
    MANV NUMBER,
    TENTN NVARCHAR2(30),
    PHAI NVARCHAR2(3),
    PRIMARY KEY (MANV, TENTN),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
--insert
--phongban
INSERT INTO PHONGBAN VALUES (1, N'IT');
INSERT INTO PHONGBAN VALUES (2, N'K? toán');
INSERT INTO PHONGBAN VALUES (3, N'Nhân s?');
INSERT INTO PHONGBAN VALUES (4, N'Marketing');
INSERT INTO PHONGBAN VALUES (5, N'K? thu?t');
--?iaiem
INSERT INTO NHANVIEN VALUES (101, N'An', 1000, 1);
INSERT INTO NHANVIEN VALUES (102, N'Bình', 1200, 1);
INSERT INTO NHANVIEN VALUES (103, N'C??ng', 900, 2);
INSERT INTO NHANVIEN VALUES (104, N'Dung', 1100, 3);
INSERT INTO NHANVIEN VALUES (105, N'Em', 1500, 4);
--diadiem_PHG
INSERT INTO DIADIEM_PHG VALUES (1, N'HCM');
INSERT INTO DIADIEM_PHG VALUES (2, N'Hà N?i');
INSERT INTO DIADIEM_PHG VALUES (3, N'?à N?ng');
INSERT INTO DIADIEM_PHG VALUES (4, N'Hu?');
INSERT INTO DIADIEM_PHG VALUES (5, N'C?n Th?');
--Dean
INSERT INTO DEAN VALUES (201, N'Web App', 1);
INSERT INTO DEAN VALUES (202, N'App Mobile', 1);
INSERT INTO DEAN VALUES (203, N'K? toán', 2);
INSERT INTO DEAN VALUES (204, N'Tuy?n d?ng', 3);
INSERT INTO DEAN VALUES (205, N'Qu?ng cáo', 4);
--Phancong
INSERT INTO PHANCONG VALUES (101, 201, 10);
INSERT INTO PHANCONG VALUES (102, 202, 15);
INSERT INTO PHANCONG VALUES (103, 203, 20);
INSERT INTO PHANCONG VALUES (104, 204, 12);
INSERT INTO PHANCONG VALUES (105, 205, 18);
--Thannhan
INSERT INTO THANNHAN VALUES (101, N'Lan', N'N?');
INSERT INTO THANNHAN VALUES (102, N'Hùng', N'Nam');
INSERT INTO THANNHAN VALUES (103, N'Mai', N'N?');
INSERT INTO THANNHAN VALUES (104, N'Tu?n', N'Nam');
INSERT INTO THANNHAN VALUES (105, N'Nga', N'N?');

