--tao bang
CREATE TABLE HangSX (
MaHangSX VARCHAR2(10) CONSTRAINT pk_hangsx PRIMARY KEY,
TenHang VARCHAR2(30) NOT NULL,
DiaChi VARCHAR2(50),
SoDT VARCHAR2(15),
Email VARCHAR2(50)
);

CREATE TABLE SanPham (
MaSP VARCHAR2(10) CONSTRAINT pk_sanpham PRIMARY KEY,
MaHangSX VARCHAR2(10) REFERENCES HangSX(MaHangSX),
TenSP VARCHAR2(50) NOT NULL,
SoLuong NUMBER(10),
MauSac VARCHAR2(20),
GiaBan NUMBER(15,2),
DonViTinh VARCHAR2(15),
MoTa CLOB
);

CREATE TABLE NhanVien (
MaNV VARCHAR2(10) CONSTRAINT pk_nhanvien PRIMARY KEY,
TenNV VARCHAR2(50) NOT NULL,
GioiTinh VARCHAR2(10),
DiaChi VARCHAR2(100),
SoDT VARCHAR2(15),
Email VARCHAR2(50),
TenPhong VARCHAR2(30)
);

CREATE TABLE PNhap (
SoHDN VARCHAR2(10) CONSTRAINT pk_pnhap PRIMARY KEY,
NgayNhap DATE,
MaNV VARCHAR2(10) REFERENCES NhanVien(MaNV)
);

CREATE TABLE Nhap (
SoHDN VARCHAR2(10) REFERENCES PNhap(SoHDN),
MaSP VARCHAR2(10) REFERENCES SanPham(MaSP),
SoLuongN NUMBER(10),
DonGiaN NUMBER(15,2),
CONSTRAINT pk_nhap PRIMARY KEY (SoHDN, MaSP)
);

CREATE TABLE PXuat (
SoHDX VARCHAR2(10) CONSTRAINT pk_pxuat PRIMARY KEY,
NgayXuat DATE,
MaNV VARCHAR2(10) REFERENCES NhanVien(MaNV)
);

CREATE TABLE Xuat (
SoHDX VARCHAR2(10) REFERENCES PXuat(SoHDX),
MaSP VARCHAR2(10) REFERENCES SanPham(MaSP),
SoLuongX NUMBER(10),
CONSTRAINT pk_xuat PRIMARY KEY (SoHDX, MaSP)
);

--phieu hoc tap 1
--sp_NhaphangSX
CREATE OR REPLACE PROCEDURE sp_NhapHangSX(
p_MaHangSX VARCHAR2,
p_TenHang VARCHAR2,
p_DiaChi VARCHAR2,
p_SoDT VARCHAR2,
p_Email VARCHAR2)
AS
v_ma VARCHAR2(10);
BEGIN
SELECT MaHangSX INTO v_ma
FROM HangSX
WHERE TenHang=p_TenHang;

EXCEPTION
WHEN NO_DATA_FOUND THEN
INSERT INTO HangSX
VALUES(p_MaHangSX,p_TenHang,p_DiaChi,p_SoDT,p_Email);
END;
--sp_NhapSP
CREATE OR REPLACE PROCEDURE sp_NhapSP(
p_MaSP VARCHAR2,
p_MaHangSX VARCHAR2,
p_TenSP VARCHAR2,
p_SoLuong NUMBER,
p_MauSac VARCHAR2,
p_GiaBan NUMBER,
p_DonViTinh VARCHAR2,
p_MoTa VARCHAR2)
AS
v_ma VARCHAR2(10);
BEGIN
SELECT MaSP INTO v_ma
FROM SanPham
WHERE MaSP=p_MaSP;
UPDATE SanPham
SET TenSP=p_TenSP,
SoLuong=p_SoLuong,
MauSac=p_MauSac,
GiaBan=p_GiaBan,
DonViTinh=p_DonViTinh,
MoTa=p_MoTa
WHERE MaSP=p_MaSP;
EXCEPTION
WHEN NO_DATA_FOUND THEN
INSERT INTO SanPham
VALUES(p_MaSP,p_MaHangSX,p_TenSP,p_SoLuong,p_MauSac,p_GiaBan,p_DonViTinh,p_MoTa);
END;
--sp_XoaHangSX
CREATE OR REPLACE PROCEDURE sp_XoaHangSX(
p_TenHang VARCHAR2)
AS
v_ma VARCHAR2(10);
BEGIN
SELECT MaHangSX INTO v_ma
FROM HangSX
WHERE TenHang=p_TenHang;
DELETE FROM SanPham
WHERE MaHangSX=v_ma;
DELETE FROM HangSX
WHERE MaHangSX=v_ma;
END;
--sp_NhapNhanVien (FLAG)
CREATE OR REPLACE PROCEDURE sp_NhapNhanVien(
p_MaNV VARCHAR2,
p_TenNV VARCHAR2,
p_GioiTinh VARCHAR2,
p_DiaChi VARCHAR2,
p_SoDT VARCHAR2,
p_Email VARCHAR2,
p_TenPhong VARCHAR2,
p_Flag NUMBER)
AS
BEGIN
IF p_Flag=0 THEN
UPDATE NhanVien
SET TenNV=p_TenNV,
GioiTinh=p_GioiTinh,
DiaChi=p_DiaChi,
SoDT=p_SoDT,
Email=p_Email,
TenPhong=p_TenPhong
WHERE MaNV=p_MaNV;
ELSE
INSERT INTO NhanVien
VALUES(p_MaNV,p_TenNV,p_GioiTinh,p_DiaChi,p_SoDT,p_Email,p_TenPhong);
END IF;
END;
--sp_NhapNhap
CREATE OR REPLACE PROCEDURE sp_NhapNhap(
p_SoHDN VARCHAR2,
p_MaSP VARCHAR2,
p_MaNV VARCHAR2,
p_NgayNhap DATE,
p_SoLuong NUMBER,
p_DonGia NUMBER)
AS
BEGIN
INSERT INTO PNhap
VALUES(p_SoHDN,p_NgayNhap,p_MaNV);
INSERT INTO Nhap
VALUES(p_SoHDN,p_MaSP,p_SoLuong,p_DonGia);
END;
--sp_NhapXuat
CREATE OR REPLACE PROCEDURE sp_NhapXuat(
p_SoHDX VARCHAR2,
p_MaSP VARCHAR2,
p_MaNV VARCHAR2,
p_NgayXuat DATE,
p_SoLuong NUMBER)
AS
v_sl NUMBER;
BEGIN
SELECT SoLuong INTO v_sl
FROM SanPham
WHERE MaSP=p_MaSP;
IF p_SoLuong>v_sl THEN
RETURN;
END IF;
INSERT INTO PXuat
VALUES(p_SoHDX,p_NgayXuat,p_MaNV);
INSERT INTO Xuat
VALUES(p_SoHDX,p_MaSP,p_SoLuong);
END;
--sp_XoaNhanVien
CREATE OR REPLACE PROCEDURE sp_XoaNhanVien(
p_MaNV VARCHAR2)
AS
BEGIN
DELETE FROM PNhap
WHERE MaNV=p_MaNV;
DELETE FROM PXuat
WHERE MaNV=p_MaNV;
DELETE FROM NhanVien
WHERE MaNV=p_MaNV;
END;
--sp_XoaSanPham
CREATE OR REPLACE PROCEDURE sp_XoaSanPham(
p_MaSP VARCHAR2)
AS
BEGIN
DELETE FROM Nhap
WHERE MaSP=p_MaSP;
DELETE FROM Xuat
WHERE MaSP=p_MaSP;
DELETE FROM SanPham
WHERE MaSP=p_MaSP;
END;
--phieu hoc tap 2
--sp_ThemNhanVien
CREATE OR REPLACE PROCEDURE sp_ThemNhanVien(
p_MaNV VARCHAR2,
p_TenNV VARCHAR2,
p_GioiTinh VARCHAR2,
p_DiaChi VARCHAR2,
p_SoDT VARCHAR2,
p_Email VARCHAR2,
p_TenPhong VARCHAR2,
p_Flag NUMBER,
KQ OUT NUMBER)
AS
BEGIN
IF p_GioiTinh<>'Nam' AND p_GioiTinh<>'Nu' THEN
KQ:=1;
RETURN;
END IF;
IF p_Flag=0 THEN
INSERT INTO NhanVien
VALUES(p_MaNV,p_TenNV,p_GioiTinh,p_DiaChi,p_SoDT,p_Email,p_TenPhong);
ELSE
UPDATE NhanVien
SET TenNV=p_TenNV
WHERE MaNV=p_MaNV;
END IF;
KQ:=0;
END;
--sp_ThemMoiSP
CREATE OR REPLACE PROCEDURE sp_ThemMoiSP(
p_MaSP VARCHAR2,
p_MaHangSX VARCHAR2,
p_TenSP VARCHAR2,
p_SoLuong NUMBER,
p_MauSac VARCHAR2,
p_GiaBan NUMBER,
p_DonViTinh VARCHAR2,
p_MoTa VARCHAR2,
p_Flag NUMBER,
KQ OUT NUMBER)
AS
v_ma VARCHAR2(10);
BEGIN
SELECT MaHangSX INTO v_ma
FROM HangSX
WHERE MaHangSX=p_MaHangSX;
IF p_SoLuong<0 THEN
KQ:=2;
RETURN;
END IF;
IF p_Flag=0 THEN
INSERT INTO SanPham
VALUES(p_MaSP,p_MaHangSX,p_TenSP,p_SoLuong,p_MauSac,p_GiaBan,p_DonViTinh,p_MoTa);
ELSE
UPDATE SanPham
SET TenSP=p_TenSP
WHERE MaSP=p_MaSP;
END IF;
KQ:=0;
EXCEPTION
WHEN NO_DATA_FOUND THEN
KQ:=1;
END;
--sp_XoaNhanVien_OUT
CREATE OR REPLACE PROCEDURE sp_XoaNhanVien_OUT(
p_MaNV VARCHAR2,
KQ OUT NUMBER)
AS
BEGIN
DELETE FROM NhanVien
WHERE MaNV=p_MaNV;
KQ:=0;
END;
--sp_XoaSanPham_OUT
CREATE OR REPLACE PROCEDURE sp_XoaSanPham_OUT(
p_MaSP VARCHAR2,
KQ OUT NUMBER)
AS
BEGIN
DELETE FROM SanPham
WHERE MaSP=p_MaSP;
KQ:=0;
END;
--sp_NhapHangSX_OUT
CREATE OR REPLACE PROCEDURE sp_NhapHangSX_OUT(
p_MaHangSX VARCHAR2,
p_TenHang VARCHAR2,
p_DiaChi VARCHAR2,
p_SoDT VARCHAR2,
p_Email VARCHAR2,
KQ OUT NUMBER)
AS
BEGIN
INSERT INTO HangSX
VALUES(p_MaHangSX,p_TenHang,p_DiaChi,p_SoDT,p_Email);
KQ:=0;
END;
--sp_NhapNhap_OUT
CREATE OR REPLACE PROCEDURE sp_NhapNhap_OUT(
p_SoHDN VARCHAR2,
p_MaSP VARCHAR2,
p_MaNV VARCHAR2,
p_NgayNhap DATE,
p_SoLuong NUMBER,
p_DonGia NUMBER,
KQ OUT NUMBER)
AS
BEGIN
INSERT INTO Nhap
VALUES(p_SoHDN,p_MaSP,p_SoLuong,p_DonGia);
KQ:=0;
END;
--sp_NhapXuat_OUT
CREATE OR REPLACE PROCEDURE sp_NhapXuat_OUT(
p_SoHDX VARCHAR2,
p_MaSP VARCHAR2,
p_MaNV VARCHAR2,
p_NgayXuat DATE,
p_SoLuong NUMBER,
KQ OUT NUMBER)
AS
BEGIN
INSERT INTO Xuat
VALUES(p_SoHDX,p_MaSP,p_SoLuong);
KQ:=0;
END;

