-- BANG MON HOC
CREATE TABLE MON_HOC (
    MA_MON_HOC       NUMBER(8,0)    NOT NULL,
    MO_TA            VARCHAR2(50),
    HOC_PHI          NUMBER(9,2),
    MON_TIEN_QUYET   NUMBER(8,0),
    NGUOI_TAO        VARCHAR2(30)    NOT NULL,
    NGAY_TAO         DATE            NOT NULL,
    NGUOI_CAP_NHAT   VARCHAR2(30)    NOT NULL,
    NGAY_CAP_NHAT    DATE            NOT NULL,
    CONSTRAINT PK_MON_HOC PRIMARY KEY (MA_MON_HOC)
);

-- BANG GIANG VIEN
CREATE TABLE GIANG_VIEN (
    MA_GIANG_VIEN    NUMBER(8,0)     NOT NULL,
    XUNG_HO          VARCHAR2(5),
    HO               VARCHAR2(25),
    TEN              VARCHAR2(25),
    DIA_CHI          VARCHAR2(50),
    DIEN_THOAI       VARCHAR2(15),
    NGUOI_TAO        VARCHAR2(30)    NOT NULL,
    NGAY_TAO         DATE            NOT NULL,
    NGUOI_CAP_NHAT   VARCHAR2(30)    NOT NULL,
    NGAY_CAP_NHAT    DATE            NOT NULL,
    CONSTRAINT PK_GIANG_VIEN PRIMARY KEY (MA_GIANG_VIEN)
);

-- BANG SINH VIEN
CREATE TABLE SINH_VIEN (
    MA_SINH_VIEN     NUMBER(8,0)     NOT NULL,
    XUNG_HO          VARCHAR2(5),
    HO               VARCHAR2(25)    NOT NULL,
    TEN              VARCHAR2(25),
    DIA_CHI          VARCHAR2(50),
    DIEN_THOAI       VARCHAR2(15),
    CONG_TY          VARCHAR2(50),
    NGAY_DANG_KY     DATE            NOT NULL,
    NGUOI_TAO        VARCHAR2(30)    NOT NULL,
    NGAY_TAO         DATE            NOT NULL,
    NGUOI_CAP_NHAT   VARCHAR2(30)    NOT NULL,
    NGAY_CAP_NHAT    DATE            NOT NULL,
    CONSTRAINT PK_SINH_VIEN PRIMARY KEY (MA_SINH_VIEN)
);

-- BANG LOP HOC
CREATE TABLE LOP_HOC (
    MA_LOP_HOC       NUMBER(8,0)     NOT NULL,
    MA_MON_HOC       NUMBER(8,0)     NOT NULL,
    SO_LOP           NUMBER(3,0)     NOT NULL,
    THOI_GIAN_BAT_DAU DATE,
    DIA_DIEM         VARCHAR2(50),
    MA_GIANG_VIEN    NUMBER(8,0)     NOT NULL,
    SISO_TOI_DA      NUMBER(3,0),
    NGUOI_TAO        VARCHAR2(30)    NOT NULL,
    NGAY_TAO         DATE            NOT NULL,
    NGUOI_CAP_NHAT   VARCHAR2(30)    NOT NULL,
    NGAY_CAP_NHAT    DATE            NOT NULL,
    CONSTRAINT PK_LOP_HOC PRIMARY KEY (MA_LOP_HOC),
    CONSTRAINT FK_LOP_MON FOREIGN KEY (MA_MON_HOC) REFERENCES MON_HOC(MA_MON_HOC),
    CONSTRAINT FK_LOP_GV  FOREIGN KEY (MA_GIANG_VIEN) REFERENCES GIANG_VIEN(MA_GIANG_VIEN)
);

-- BANG DANG KY
CREATE TABLE DANG_KY (
    MA_SINH_VIEN     NUMBER(8,0)     NOT NULL,
    MA_LOP_HOC       NUMBER(8,0)     NOT NULL,
    NGAY_DANG_KY_LOP DATE            NOT NULL,
    DIEM_TONG_KET    NUMBER(3,0),
    NGUOI_TAO        VARCHAR2(30)    NOT NULL,
    NGAY_TAO         DATE            NOT NULL,
    NGUOI_CAP_NHAT   VARCHAR2(30)    NOT NULL,
    NGAY_CAP_NHAT    DATE            NOT NULL,
    CONSTRAINT PK_DANG_KY PRIMARY KEY (MA_SINH_VIEN, MA_LOP_HOC),
    CONSTRAINT FK_DK_SV FOREIGN KEY (MA_SINH_VIEN) REFERENCES SINH_VIEN(MA_SINH_VIEN),
    CONSTRAINT FK_DK_LOP FOREIGN KEY (MA_LOP_HOC) REFERENCES LOP_HOC(MA_LOP_HOC)
);

-- BANG DIEM
CREATE TABLE DIEM (
    MA_SINH_VIEN     NUMBER(8,0)     NOT NULL,
    MA_LOP_HOC       NUMBER(8,0)     NOT NULL,
    DIEM_SO          NUMBER(3,0)     NOT NULL,
    NHAN_XET         VARCHAR2(2000),
    NGUOI_TAO        VARCHAR2(30)    NOT NULL,
    NGAY_TAO         DATE            NOT NULL,
    NGUOI_CAP_NHAT   VARCHAR2(30)    NOT NULL,
    NGAY_CAP_NHAT    DATE            NOT NULL,
    CONSTRAINT PK_DIEM PRIMARY KEY (MA_SINH_VIEN, MA_LOP_HOC),
    CONSTRAINT FK_DIEM_DANGKY FOREIGN KEY (MA_SINH_VIEN, MA_LOP_HOC)
        REFERENCES DANG_KY(MA_SINH_VIEN, MA_LOP_HOC)
);

-- KHOA NGOAI TU THAM CHIEU CHO MON_HOC
ALTER TABLE MON_HOC
ADD CONSTRAINT FK_MON_TIEN_QUYET
FOREIGN KEY (MON_TIEN_QUYET) REFERENCES MON_HOC(MA_MON_HOC);
--insert
-- 1. MON_HOC
INSERT INTO MON_HOC VALUES (1, 'Co so du lieu', 1000000, NULL, USER, SYSDATE, USER, SYSDATE);
INSERT INTO MON_HOC VALUES (2, 'Lap trinh Java', 1200000, NULL, USER, SYSDATE, USER, SYSDATE);
INSERT INTO MON_HOC VALUES (3, 'Mang may tinh', 900000, NULL, USER, SYSDATE, USER, SYSDATE);

-- 2. GIANG_VIEN
INSERT INTO GIANG_VIEN VALUES (1, NULL, 'Nguyen', 'A', NULL, NULL, USER, SYSDATE, USER, SYSDATE);
INSERT INTO GIANG_VIEN VALUES (2, NULL, 'Tran', 'B', NULL, NULL, USER, SYSDATE, USER, SYSDATE);
INSERT INTO GIANG_VIEN VALUES (3, NULL, 'Le', 'C', NULL, NULL, USER, SYSDATE, USER, SYSDATE);

-- 3. SINH_VIEN
INSERT INTO SINH_VIEN VALUES (1, NULL, 'Pham', 'An', NULL, NULL, NULL, SYSDATE, USER, SYSDATE, USER, SYSDATE);
INSERT INTO SINH_VIEN VALUES (2, NULL, 'Vo', 'Binh', NULL, NULL, NULL, SYSDATE, USER, SYSDATE, USER, SYSDATE);
INSERT INTO SINH_VIEN VALUES (3, NULL, 'Do', 'Cuong', NULL, NULL, NULL, SYSDATE, USER, SYSDATE, USER, SYSDATE);
INSERT INTO SINH_VIEN VALUES (4, NULL, 'Hoang', 'Dung', NULL, NULL, NULL, SYSDATE, USER, SYSDATE, USER, SYSDATE);

-- 4. LOP_HOC
-- GV 1 d?y nhi?u l?p nh?t
INSERT INTO LOP_HOC VALUES (1, 1, 1, SYSDATE, NULL, 1, 30, USER, SYSDATE, USER, SYSDATE);
INSERT INTO LOP_HOC VALUES (2, 1, 2, SYSDATE, NULL, 1, 30, USER, SYSDATE, USER, SYSDATE);
INSERT INTO LOP_HOC VALUES (3, 2, 1, SYSDATE, NULL, 1, 30, USER, SYSDATE, USER, SYSDATE);

-- GV 2 ít l?p
INSERT INTO LOP_HOC VALUES (4, 2, 2, SYSDATE, NULL, 2, 30, USER, SYSDATE, USER, SYSDATE);

-- GV 3 trung bình
INSERT INTO LOP_HOC VALUES (5, 3, 1, SYSDATE, NULL, 3, 30, USER, SYSDATE, USER, SYSDATE);
INSERT INTO LOP_HOC VALUES (6, 3, 2, SYSDATE, NULL, 3, 30, USER, SYSDATE, USER, SYSDATE);

-- 5. DANG_KY

-- SV 1 h?c nhi?u nh?t (3 l?p)
INSERT INTO DANG_KY VALUES (1, 1, SYSDATE, 90, USER, SYSDATE, USER, SYSDATE);
INSERT INTO DANG_KY VALUES (1, 2, SYSDATE, 85, USER, SYSDATE, USER, SYSDATE);
INSERT INTO DANG_KY VALUES (1, 3, SYSDATE, 88, USER, SYSDATE, USER, SYSDATE);

-- SV 2 h?c ít (1 l?p)
INSERT INTO DANG_KY VALUES (2, 1, SYSDATE, 70, USER, SYSDATE, USER, SYSDATE);

-- SV 3 h?c trung bình (2 l?p)
INSERT INTO DANG_KY VALUES (3, 2, SYSDATE, 60, USER, SYSDATE, USER, SYSDATE);
INSERT INTO DANG_KY VALUES (3, 3, SYSDATE, 75, USER, SYSDATE, USER, SYSDATE);

-- SV 4 h?c 1 l?p
INSERT INTO DANG_KY VALUES (4, 4, SYSDATE, 50, USER, SYSDATE, USER, SYSDATE);

-- 6. DIEM 
INSERT INTO DIEM VALUES (1, 1, 90, NULL, USER, SYSDATE, USER, SYSDATE);
INSERT INTO DIEM VALUES (2, 1, 70, NULL, USER, SYSDATE, USER, SYSDATE);
INSERT INTO DIEM VALUES (3, 2, 60, NULL, USER, SYSDATE, USER, SYSDATE);

COMMIT;
--Cac cau hoi bai tap
--Bai1
--cau1a
CREATE TABLE Cau1 (
    ID NUMBER,
    NAME VARCHAR2(20)
);

--cau1b
CREATE SEQUENCE Cau1Seq
START WITH 5
INCREMENT BY 5;

--cau1c
DECLARE
    v_name VARCHAR2(50);
    v_id NUMBER;
BEGIN
    NULL;  
END;

--cau1d
SELECT HO || ' ' || TEN
INTO v_name
FROM SINH_VIEN
WHERE MA_SINH_VIEN = (
    SELECT MA_SINH_VIEN
    FROM (
        SELECT MA_SINH_VIEN
        FROM DANG_KY
        GROUP BY MA_SINH_VIEN
        HAVING COUNT(*) = (
            SELECT MAX(cnt)
            FROM (
                SELECT COUNT(*) cnt
                FROM DANG_KY
                GROUP BY MA_SINH_VIEN
            )
        )
    )
    WHERE ROWNUM = 1
);
----cau1e
SELECT firstname || ' ' || lastname
INTO v_name
FROM student
WHERE studentid = (
    SELECT studentid FROM enrollment
    GROUP BY studentid
    HAVING COUNT(*) = (
        SELECT MIN(COUNT(*))
        FROM enrollment
        GROUP BY studentid
    )
    FETCH FIRST 1 ROWS ONLY
);
INSERT INTO Cau1 VALUES (Cau1Seq.NEXTVAL, v_name);
SAVEPOINT sp_b;
SELECT * FROM CAU1;
----cau1f
SELECT i.firstname || ' ' || i.lastname
INTO v_name
FROM instructor i
WHERE i.instructorid = (
    SELECT instructorid FROM class
    GROUP BY instructorid
    HAVING COUNT(*) = (
        SELECT MAX(COUNT(*))
        FROM class
        GROUP BY instructorid
    )
    FETCH FIRST 1 ROWS ONLY
);

INSERT INTO Cau1 (ID, NAME)
VALUES (Cau1Seq.NEXTVAL, v_name);

SAVEPOINT sp_c;

----cau1g
SELECT ID INTO v_id
FROM Cau1
WHERE NAME = v_name;

DBMS_OUTPUT.PUT_LINE('ID giao vien nhieu lop: ' || v_id);

--cau1h
ROLLBACK TO sp_b;

--cau1i
SELECT i.firstname || ' ' || i.lastname
INTO v_name
FROM instructor i
WHERE i.instructorid = (
    SELECT instructorid FROM class
    GROUP BY instructorid
    HAVING COUNT(*) = (
        SELECT MIN(COUNT(*))
        FROM class
        GROUP BY instructorid
    )
    FETCH FIRST 1 ROWS ONLY
);

INSERT INTO Cau1 (ID, NAME)
VALUES (v_id, v_name);

--cau1j
SELECT i.firstname || ' ' || i.lastname
INTO v_name
FROM instructor i
WHERE i.instructorid = (
    SELECT instructorid FROM class
    GROUP BY instructorid
    HAVING COUNT(*) = (
        SELECT MAX(COUNT(*))
        FROM class
        GROUP BY instructorid
    )
    FETCH FIRST 1 ROWS ONLY
);

INSERT INTO Cau1 (ID, NAME)
VALUES (Cau1Seq.NEXTVAL, v_name);

COMMIT;

DBMS_OUTPUT.PUT_LINE('Hoan tat!');

EXCEPTION
WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('Khong tim thay du lieu!');
    ROLLBACK;
WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Loi: ' || SQLERRM);
    ROLLBACK;
END;